QLLaCoffee/QLLaCoffee/Areas/Admin/Controllers/GoodsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using QLLaCoffee.App_Start;
using QLLaCoffee.Models;

namespace QLLaCoffee.Areas.Admin.Controllers
{
    public class GoodsController : Controller
    {
        private LaCoffeeDBContext db = new LaCoffeeDBContext();

        [RoleUser(FunctionID = "MH_Xem")]
        public ActionResult Index()
        {
            var goods = db.Goods.Include(g => g.GoodsCategories);
            ViewBag.GoodsID = new SelectList(db.Goods, "GoodsID", "GoodsName");
            return View(goods.ToList());
        }

        [HttpPost]
        public ActionResult Index(string goodsName, string goodsCategoryName, string goodsUnit, decimal? minPrice, decimal? maxPrice, int? minCount, int? maxCount)
        { 
            ViewBag.GoodsName = goodsName;
            ViewBag.GoodsCategoryName = goodsCategoryName;
            ViewBag.GoodsUnit = goodsUnit;
            ViewBag.MinPrice = minPrice;
            ViewBag.MaxPrice = maxPrice;
            ViewBag.MinCount = minCount;
            ViewBag.MaxCount = maxCount;
            var result = (from item in db.Goods
                          where (item.GoodsName.ToLower().Contains(goodsName.ToLower()) || string.IsNullOrEmpty(goodsName)) &&
                                 (item.GoodsCategories.GoodsCategoryName.ToLower().Contains(goodsCategoryName.ToLower()) || string.IsNullOrEmpty(goodsCategoryName)) &&
                                 (item.GoodsUnit.ToLower().Contains(goodsUnit.ToLower()) || string.IsNullOrEmpty(goodsUnit)) &&
                                 (item.GoodsCount >= minCount || minCount == null) &&
                                 (item.GoodsCount <= maxCount || maxCount == null) &&
                                 (item.GoodsPrice >= minPrice || minPrice == null) &&
                                 (item.GoodsPrice <= maxPrice || maxPrice == null)
                          select item).ToList();
            return View(result);
        }

        [RoleUser(FunctionID = "MH_Them")]
        public ActionResult Create()
        {
            ViewBag.GoodsCategoryID = new SelectList(db.GoodsCategories, "GoodsCategoryID", "GoodsCategoryName");
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Goods goods)
        {
            if (ModelState.IsValid)
            {
                db.Goods.Add(goods);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.GoodsCategoryID = new SelectList(db.GoodsCategories, "GoodsCategoryID", "GoodsCategoryName", goods.GoodsCategoryID);
            return View(goods);
        }

        [RoleUser(FunctionID = "MH_Sua")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Goods goods = db.Goods.Find(id);
            if (goods == null)
            {
                return HttpNotFound();
            }
            ViewBag.GoodsCategoryID = new SelectList(db.GoodsCategories, "GoodsCategoryID", "GoodsCategoryName", goods.GoodsCategoryID);
            return View(goods);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Goods goods)
        {
            if (ModelState.IsValid)
            {
                db.Entry(goods).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.GoodsCategoryID = new SelectList(db.GoodsCategories, "GoodsCategoryID", "GoodsCategoryName", goods.GoodsCategoryID);
            return View(goods);
        }

        [HttpPost]
        [RoleUser(FunctionID = "MH_Xoa")]
        public ActionResult Delete(int id)
        {
            Goods goods = db.Goods.Find(id);
            db.Goods.Remove(goods);
            db.SaveChanges();
            return Json(new { success = true });
        }

        [HttpPost]
        [RoleUser(FunctionID = "MH_Xoa")]
        public ActionResult DeleteAll(string ids)
        {
            if (!string.IsNullOrEmpty(ids))
            {
                var items = ids.Split(',');
                if (items != null && items.Any())
                {
                    foreach (var item in items)
                    {
                        var o = db.Goods.Find(Convert.ToInt32(item));
                        db.Goods.Remove(o);
                        db.SaveChanges();
                    }
                }
                return Json(new { success = true });
            }
            return Json(new { success = false });
        }
    }
}

QLLaCoffee/QLLaCoffee/Areas/Admin/Controllers/SellController.cs
using Antlr.Runtime.Misc;
using QLLaCoffee.App_Start;
using QLLaCoffee.Models;
using SelectPdf;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Drawing.Printing;
using System.Dynamic;
using System.IO;
using System.Linq;
using System.Net;
using System.Security.Cryptography.X509Certificates;
using System.Web;
using System.Web.Mvc;
using System.Web.UI.WebControls;

namespace QLLaCoffee.Areas.Admin.Controllers
{
    [RoleUser(FunctionID = "BH_QuanLy")]
    public class SellController : BaseController
    {
        private LaCoffeeDBContext db = new LaCoffeeDBContext();

        [RoleUser]
        public ActionResult Index()
        {
            return View(db.Tables.ToList());
        }

        [RoleUser]
        public ActionResult Order(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Tables table = db.Tables.Find(id);
            if (table == null)
            {
                return HttpNotFound();
            }
            ViewBag.TableName = table.TableName;
            ViewBag.ListDrinks = db.Drinks.ToList();
            ViewBag.ListDrinkCategories = db.Drinks.Select(p => p.DrinkCategories).Distinct().ToList();
            TempData["TableID"] = table.TableID;
            Bills bills = db.Bills.Where(b => b.TableID == id).FirstOrDefault();
            if (bills != null)
            {
                ViewBag.check = true;
                return View(bills.BillInfos.ToList());
            }
            else
            {
                ViewBag.check = false;
                table.Status = false;
                db.Entry(table).State = EntityState.Modified;
                db.SaveChanges();
                return View(db.BillInfos.ToList());
            }
        }

        [RoleUser]
        public ActionResult SelectDrinkByCategory(int id)
        {
            var drinks = from d in db.Drinks where d.DrinkCategoryID == id select d;
            return View("Order", drinks);
        }

        [RoleUser]
        public ActionResult AddDrinkToBill(int id)
        {
            int? tableID = TempData["TableID"] as int?;
            Drinks drink = db.Drinks.Find(id);
            BillInfos billInfo = new BillInfos();
            Tables table = db.Tables.Find(tableID);
            billInfo.DrinkID = id;
            billInfo.DrinkCount = 1;
            billInfo.DrinkPrice = drink.DrinkPrice * billInfo.DrinkCount;
            if (table.Status == false && !table.Bills.Any())
            {
                Bills bills = new Bills();
                bills.BillID = "HD" + DateTime.Now.Month + DateTime.Now.Day + Guid.NewGuid().ToString().Substring(0, 8);
                Session["Bills"] = bills.BillID;
                bills.CreateDate = DateTime.Now;
                bills.TotalAmount = billInfo.DrinkPrice;
                bills.TableID = (int)tableID;
                bills.UserID = SessionConfig.GetUser().UserID;
                billInfo.BillID = bills.BillID;
                db.Bills.Add(bills);
                db.BillInfos.Add(billInfo);
                table.Status = true;
                table.Bills.Add(bills);
                db.Entry(table).State = EntityState.Modified;
                db.SaveChanges();
            }
            else
            {
                Bills bills = db.Bills.Where(b => b.TableID == tableID).FirstOrDefault();
                BillInfos existingBillInfo = db.BillInfos.FirstOrDefault(bi => bi.BillID == bills.BillID && bi.DrinkID == id);
                if (existingBillInfo != null)
                {
                    existingBillInfo.DrinkCount += 1;
                    existingBillInfo.DrinkPrice = existingBillInfo.DrinkCount * drink.DrinkPrice;
                    db.Entry(existingBillInfo).State = EntityState.Modified;
                    db.SaveChanges();
                }
                else
                {
                    billInfo.BillID = bills.BillID;
                    db.BillInfos.Add(billInfo);
                    db.SaveChanges();
                }

                bills.TotalAmount = db.BillInfos
                    .Where(bi => bi.BillID == bills.BillID)
                    .Sum(bi => bi.DrinkPrice);
                db.Entry(bills).State = EntityState.Modified;
                db.SaveChanges();
            }
            return RedirectToAction("Order", new { id = tableID });
        }

        [RoleUser]
        public ActionResult ExportPDF()
        {
            HtmlToPdf converter = new HtmlToPdf();
            converter.Options.PdfPageSize = PdfPageSize.A6;
            converter.Options.PdfPageOrientation = PdfPageOrientation.Portrait;
            converter.Options.MarginLeft = 10;
            converter.Options.MarginRight = 10;
            converter.Options.MarginTop = 20;
            converter.Options.MarginBottom = 20;
            int? tableID = TempData["TableID"] as int?;
            Bills bills = db.Bills.Where(b => b.TableID == tableID).FirstOrDefault();
            bills.CreateDate = DateTime.Now;
            db.Entry(bills).State = EntityState.Modified;
            db.SaveChanges();
            var list = bills.BillInfos.ToList();
            var htmlPDF = base.RenderPartialToString("~/Areas/Admin/Views/Sell/HoaDonTamTinh.cshtml", list);
            PdfDocument doc = converter.ConvertHtmlString(htmlPDF);
            string fileName = string.Format("{0}.pdf", bills.BillID + "temp");
            string pathFile = Path.Combine(Server.MapPath("~/Public/PDF"), fileName);
            doc.Save(pathFile);
            doc.Close();
            return Json(new { success = true }, JsonRequestBehavior.AllowGet);
        }

        [RoleUser]
        public ActionResult ThanhToan()
        {
            int? tableID = TempData["TableID"] as int?;
            Tables table = db.Tables.Find(tableID);
            table.Status = false;
            Bills bills = db.Bills.Where(b => b.TableID == tableID).FirstOrDefault();
            bills.TableID = null;
            bills.CreateDate = DateTime.Now;
            db.Entry(bills).State = EntityState.Modified;
            db.SaveChanges();
            return Json(new { success = true }, JsonRequestBehavior.AllowGet);
        }


        [HttpPost]
        [RoleUser]
        public ActionResult Delete(int idDrink, String idBill)
        {
            BillInfos billInfos = db.BillInfos.Find(idBill, idDrink);
            Bills bills = db.Bills.Find(idBill);
            db.BillInfos.Remove(billInfos);
            db.SaveChanges();
            if (!db.BillInfos.Any(b => b.BillID.Equals(idBill)))
            {

                db.Bills.Remove(bills);
                db.SaveChanges();
            }
            else
            {
                bills.TotalAmount = db.BillInfos
                   .Where(bi => bi.BillID == bills.BillID)
                   .Sum(bi => bi.DrinkPrice);
                db.Entry(bills).State = EntityState.Modified;
                db.SaveChanges();
            }
           ;
            return Json(new { success = true });
        }

        [RoleUser]
        public ActionResult GiamSoLuong(int idDrink, String idBill)
        {
            int? tableID = TempData["TableID"] as int?;
            BillInfos billInfos = db.BillInfos.Find(idBill, idDrink);
            Drinks drinks = db.Drinks.Find(idDrink);
            Bills bills = db.Bills.Find(idBill);
            billInfos.DrinkCount--;
            billInfos.DrinkPrice = drinks.DrinkPrice * billInfos.DrinkCount;
            db.Entry(billInfos).State = EntityState.Modified;
            db.SaveChanges();
            bills.TotalAmount = db.BillInfos
                 .Where(bi => bi.BillID == bills.BillID)
                 .Sum(bi => bi.DrinkPrice);
            db.Entry(bills).State = EntityState.Modified;
            db.SaveChanges();
            if (billInfos.DrinkCount == 0)
            {
                db.BillInfos.Remove(billInfos);
                db.SaveChanges();
                if (!db.BillInfos.Any(b => b.BillID.Equals(idBill)))
                {
                    db.Bills.Remove(bills);
                    db.SaveChanges();
                }
            }
            return RedirectToAction("Order", new { id = tableID });
        }

        [RoleUser]
        public ActionResult TangSoLuong(int idDrink, String idBill)
        {
            int? tableID = TempData["TableID"] as int?;
            BillInfos billInfos = db.BillInfos.Find(idBill, idDrink);
            Drinks drinks = db.Drinks.Find(idDrink);
            Bills bills = db.Bills.Find(idBill);
            billInfos.DrinkCount++;
            billInfos.DrinkPrice = drinks.DrinkPrice * billInfos.DrinkCount;
            db.Entry(billInfos).State = EntityState.Modified;
            db.SaveChanges();
            bills.TotalAmount = db.BillInfos
                   .Where(bi => bi.BillID == bills.BillID)
                   .Sum(bi => bi.DrinkPrice);
            db.Entry(bills).State = EntityState.Modified;
            db.SaveChanges();
            if (billInfos.DrinkCount == 0)
            {
                db.BillInfos.Remove(billInfos);
                db.SaveChanges();
                if (!db.BillInfos.Any(b => b.BillID.Equals(idBill)))
                {
                    db.Bills.Remove(bills);
                    db.SaveChanges();
                }
            }
            return RedirectToAction("Order", new { id = tableID });
        }

        [HttpPost]
        [RoleUser(FunctionID = "B_ThayDoi")]
        public ActionResult ChangeTableCount(int? tableCount)
        {
            if (tableCount != null)
            {
                db.Tables.RemoveRange(db.Tables.ToList());
                for (int i = 1; i <= tableCount; i++)
                {
                    db.Tables.Add(new Tables("Bàn " + i, false));
                }
                db.SaveChanges();
            }
            return RedirectToAction("Index");
        }

QLLaCoffee/QLLaCoffee/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>@ViewBag.Title</title>
    <link href="https://cdn.materialdesignicons.com/6.5.95/css/materialdesignicons.min.css" rel="stylesheet">
    <!-- plugins:css -->
    <link rel="stylesheet" href="~/Public/vendors/feather/feather.css">
    <link rel="stylesheet" href="~/Public/vendors/ti-icons/css/themify-icons.css">
    <link rel="stylesheet" href="~/Public/vendors/css/vendor.bundle.base.css">
    <link rel="stylesheet" href="~/Public/vendors/select2/select2.min.css">
    <link rel="stylesheet" href="~/Public/vendors/select2-bootstrap-theme/select2-bootstrap.min.css">
    <!-- endinject -->
    <!-- Plugin css for this page -->
    <link rel="stylesheet" href="~/Public/vendors/datatables.net-bs4/dataTables.bootstrap4.css">
    <link rel="stylesheet" href="~/Public/vendors/ti-icons/css/themify-icons.css">
    <link rel="stylesheet" type="text/css" href="~/Public/js/select.dataTables.min.css">
    <!-- End plugin css for this page -->
    <!-- inject:css -->
    <link rel="stylesheet" href="~/Public/css/vertical-layout-light/style.css">
    <!-- endinject -->
    <link rel="shortcut icon" href="~/Public/images/favicon.png" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/sweetalert2@10/dist/sweetalert2.min.css">
</head>
<body>
    <div class="container-scroller">
        <!-- partial:partials/_navbar.html -->
        <nav class="navbar col-lg-12 col-12 p-0 fixed-top d-flex flex-row">
            <div class="text-center navbar-brand-wrapper d-flex align-items-center justify-content-center">
                <div class="navbar-brand brand-logo h-100"><img src="~/Public/images/logo.png" alt="logo" class="h-100" /></div>
            </div>
            <div class="navbar-menu-wrapper d-flex align-items-center justify-content-end" style="background-color: dodgerblue; color: white">
                <button class="navbar-toggler navbar-toggler align-self-center" type="button" data-toggle="minimize">
                    <span class="icon-menu"></span>
                </button>
                @{
                    var user = QLLaCoffee.App_Start.SessionConfig.GetUser();
                }
                @if (user != null)
                {
                    <ul class="navbar-nav navbar-nav-right">
                        <li class="nav-item">
                            @user.FullName
                        </li>
                        <li class="nav-item nav-profile dropdown">
                            @if (user.UserImage != null)
                            {
                                <img src="~/Public/images/users/@user.UserImage" alt="profile" />

                            }
                            else
                            {
                                <img src="~/Public/images/avatar.jpg" alt="profile" />
                            }
                        </li>
                        <li class="nav-item">
                            <a class="btn btn-danger" href="@Url.Action("Logout", "Login", new { area = "" })">Đăng xuất</a>
                        </li>
                    </ul>
                }

            </div>
        </nav>
        <!-- partial -->
        <div class="container-fluid page-body-wrapper">
            <!-- partial:partials/_settings-panel.html -->
            <!-- partial -->
            <!-- partial:partials/_sidebar.html -->
            <nav class="sidebar sidebar-offcanvas position-fixed" id="sidebar">
                <ul class="nav">
                    @if (user.UserCategories.UserCategoryName == "Quản lý" || user.UserCategories.UserCategoryName == "Thu ngân")
                    {
                        <li class="nav-item">
                            <a class="nav-link" href="@Url.Action("Index", "Sell")">
                                <i class="mdi mdi-store menu-icon"></i>
                                <span class="menu-title">Bán hàng</span>
                            </a>
                        </li>
                    }
                    @if (user.UserCategories.UserCategoryName == "Quản lý")
                    {
                        <li class="nav-item">
                            <a class="nav-link" data-toggle="collapse" href="#douong" aria-expanded="false" aria-controls="douong">
                                <i class="mdi mdi-food-fork-drink menu-icon"></i>
                                <span class="menu-title">Đồ uống</span>
                                <i class="menu-arrow"></i>
                            </a>
                            <div class="collapse" id="douong">
                                <ul class="nav flex-column sub-menu">
                                    <li class="nav-item"> <a class="nav-link" href="@Url.Action("Index", "Drinks")">Đồ uống</a></li>
                                    <li class="nav-item"> <a class="nav-link" href="@Url.Action("Index", "DrinkCategories")">Loại đồ uống</a></li>
                                </ul>
                            </div>
                        </li>
                    }
                    @if (user.UserCategories.UserCategoryName == "Quản lý kho")
                    {
                        <li class="nav-item">
                            <a class="nav-link" data-toggle="collapse" href="#mathang" aria-expanded="false" aria-controls="mathang">
                                <i class="mdi mdi-dropbox menu-icon"></i>
                                <span class="menu-title">Mặt hàng</span>
                                <i class="menu-arrow"></i>
                            </a>
                            <div class="collapse" id="mathang">
                                <ul class="nav flex-column sub-menu">
                                    <li class="nav-item"> <a class="nav-link" href="@Url.Action("Index", "Goods")">Mặt hàng</a></li>
                                    <li class="nav-item"> <a class="nav-link" href="@Url.Action("Index", "GoodsCategories")">Loại mặt hàng</a></li>
                                </ul>
                            </div>
                        </li>
                    }
                    @if (user.UserCategories.UserCategoryName == "Quản lý" || user.UserCategories.UserCategoryName == "Thu ngân")
                    {
                        <li class="nav-item">
                            <a class="nav-link" href="@Url.Action("Index", "Bills")">
                                <i class="mdi mdi-clipboard-text menu-icon"></i>
                                <span class="menu-title">Hóa đơn</span>
                            </a>
                        </li>
                    }
                    @if (user.UserCategories.UserCategoryName == "Thu ngân")
                    {
                        <li class="nav-item">
                            <a class="nav-link" href="@Url.Action("Index", "ShiftReports")">
                                <i class="mdi mdi-clipboard-arrow-left menu-icon"></i>
                                <span class="menu-title">Kết ca</span>
                            </a>
                        </li>
                    }
                    @if (user.UserCategories.UserCategoryName == "Quản lý")
                    {
                        <li class="nav-item">
                            <a class="nav-link" href="@Url.Action("DanhSach", "ShiftReports")">
                                <i class="mdi mdi-bulletin-board menu-icon"></i>
                                <span class="menu-title">Báo cáo kết ca</span>
                            </a>
                        </li>
                    }
                    @if (user.UserCategories.UserCategoryName == "Quản lý")
                    {
                        <li class="nav-item">
                            <a class="nav-link" data-toggle="collapse" href="#nguoidung" aria-expanded="false" aria-controls="nguoidung">
                                <i class="mdi mdi-account menu-icon"></i>
                                <span class="menu-title">Người dùng</span>
                                <i class="menu-arrow"></i>
                            </a>
                            <div class="collapse" id="nguoidung">
                                <ul class="nav flex-column sub-menu">
                                    <li class="nav-item"> <a class="nav-link" href="@Url.Action("Index", "Users")">Người dùng</a></li>
                                    <li class="nav-item"> <a class="nav-link" href="@Url.Action("Index", "UserCategories")">Loại người dùng</a></li>
                                </ul>
                            </div>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="@Url.Action("Index", "Authorizations")">
                                <i class="mdi mdi-shield menu-icon"></i>
                                <span class="menu-title">Phân quyền</span>
                            </a>
                        </li>
                    }
                    @if (user.UserCategories.UserCategoryName == "Quản lý kho")
                    {
                        <li class="nav-item">
                            <a class="nav-link" href="@Url.Action("Index", "ThongKe")">
                                <i class="mdi mdi-chart-bar menu-icon"></i>
                                <span class="menu-title">Thống kê</span>
                            </a>
                        </li>
                    }
                </ul>
            </nav>
            <!-- partial -->
            <div class="main-panel position-absolute h-100" style="right: 0">
                <div class="content-wrapper">
                    @RenderBody()
                    <!-- main-panel ends -->
                </div>
                <!-- page-body-wrapper ends -->
            </div>
        </div>
    </div>
    <!-- container-scroller -->
    <!-- plugins:js -->
    <script src="~/Public/vendors/js/vendor.bundle.base.js"></script>
    <!-- endinject -->
    <!-- Plugin js for this page -->
    <script src="~/Public/vendors/chart.js/Chart.min.js"></script>
    <script src="~/Public/vendors/datatables.net/jquery.dataTables.js"></script>
    <script src="~/Public/vendors/datatables.net-bs4/dataTables.bootstrap4.js"></script>
    <script src="~/Public/js/dataTables.select.min.js"></script>
    <script src="~/Public/vendors/typeahead.js/typeahead.bundle.min.js"></script>
    <script src="~/Public/vendors/select2/select2.min.js"></script>

    <!-- End plugin js for this page -->
    <!-- inject:js -->
    <script src="~/Public/js/off-canvas.js"></script>
    <script src="~/Public/js/hoverable-collapse.js"></script>
    <script src="~/Public/js/template.js"></script>
    <script src="~/Public/js/settings.js"></script>
    <script src="~/Public/js/todolist.js"></script>
    <!-- endinject -->
    <!-- Custom js for this page-->
    <script src="~/Public/js/file-upload.js"></script>
    <script src="~/Public/js/dashboard.js"></script>
    <script src="~/Public/js/Chart.roundedBarCharts.js"></script>
    <script src="~/Public/js/typeahead.js"></script>
    <script src="~/Public/js/select2.js"></script>
    <!-- End custom js for this page-->
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@10"></script>
    @RenderSection("Scripts", false)
</body>

</html>