QLLaCoffee/QLLaCoffee/Areas/Admin/Controllers/GoodsCategoriesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using QLLaCoffee.App_Start;
using QLLaCoffee.Models;

namespace QLLaCoffee.Areas.Admin.Controllers
{
    [RoleUser(FunctionID = "LMH_QuanLy")]
    public class GoodsCategoriesController : Controller
    {
        private LaCoffeeDBContext db = new LaCoffeeDBContext();

        public ActionResult Index()
        {
            return View(db.GoodsCategories.ToList());
        }

        [HttpPost]
        public ActionResult Index(string goodsCategoryName)
        {
            ViewBag.GoodsCategoryName = goodsCategoryName;
            var result = (from item in db.GoodsCategories
                          where (item.GoodsCategoryName.ToLower().Contains(goodsCategoryName.ToLower()) || string.IsNullOrEmpty(goodsCategoryName))                
                          select item).ToList();
            return View(result);
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(GoodsCategories goodsCategories)
        {
            if (ModelState.IsValid)
            {
                db.GoodsCategories.Add(goodsCategories);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(goodsCategories);
        }

        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            GoodsCategories goodsCategories = db.GoodsCategories.Find(id);
            if (goodsCategories == null)
            {
                return HttpNotFound();
            }
            return View(goodsCategories);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(GoodsCategories goodsCategories)
        {
            if (ModelState.IsValid)
            {
                db.Entry(goodsCategories).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(goodsCategories);
        }

        [HttpPost]
        public ActionResult Delete(int id)
        {
            GoodsCategories goodsCategory = db.GoodsCategories.Find(id);
            db.GoodsCategories.Remove(goodsCategory);
            db.SaveChanges();
            return Json(new { success = true });
        }

        [HttpPost]
        public ActionResult DeleteAll(string ids)
        {
            if (!string.IsNullOrEmpty(ids))
            {
                var items = ids.Split(',');
                if (items != null && items.Any())
                {
                    foreach (var item in items)
                    {
                        var o = db.GoodsCategories.Find(Convert.ToInt32(item));
                        db.GoodsCategories.Remove(o);
                        db.SaveChanges();
                    }
                }
                return Json(new { success = true });
            }
            return Json(new { success = false });
        }
    }
}

QLLaCoffee/QLLaCoffee/Areas/Admin/Views/GoodsCategories/Create.cshtml
@model QLLaCoffee.Models.GoodsCategories

@{
    ViewBag.Title = "Thêm loại mặt hàng";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <div class="card">
        <div class="card-body">
            <div class="d-flex justify-content-between">
                <p class="card-title">Thêm loại mặt hàng</p>
                <a href="@Url.Action("Index", "GoodsCategories")" class="btn btn-primary">
                    <i class="ti-arrow-left"></i>
                </a>
            </div>
            <div class="table-responsive">
                <div class="form-horizontal">
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    <div class="form-group">
                        <label class="control-labe col-md-12">Tên loại mặt hàng<span class="text-danger"> (*)</span></label>
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.GoodsCategoryName, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.GoodsCategoryName, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="control-labe col-md-12">Mô tả</label>
                        <div class="col-md-10">
                            @Html.TextAreaFor(model => model.GoodsCategoryDescription, new { @class = "form-control", @rows = "4" })
                            @Html.ValidationMessageFor(model => model.GoodsCategoryDescription, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-10">
                            <button type="submit" class="btn btn-info btn-icon-text"><i class="ti-file btn-icon-prepend"></i>Lưu</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
}

QLLaCoffee/QLLaCoffee/Areas/Admin/Views/GoodsCategories/Edit.cshtml
@model QLLaCoffee.Models.GoodsCategories

@{
    ViewBag.Title = "Chỉnh sửa loại mặt hàng";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <div class="card">
        <div class="card-body">
            <div class="d-flex justify-content-between">
                <p class="card-title">Chỉnh sửa loại mặt hàng</p>
                <a href="@Url.Action("Index", "GoodsCategories")" class="btn btn-primary">
                    <i class="ti-arrow-left"></i>
                </a>
            </div>
            <div class="table-responsive">
                <div class="form-horizontal">
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    @Html.HiddenFor(model => model.GoodsCategoryID)

                    <div class="form-group">
                        <label class="control-labe col-md-12">Tên loại mặt hàng<span class="text-danger"> (*)</span></label>
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.GoodsCategoryName, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.GoodsCategoryName, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="control-labe col-md-12">Mô tả</label>
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.GoodsCategoryDescription, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.GoodsCategoryDescription, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-10">
                            <button type="submit" class="btn btn-info btn-icon-text"><i class="ti-file btn-icon-prepend"></i>Lưu</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
}

QLLaCoffee/QLLaCoffee/Areas/Admin/Views/GoodsCategories/Index.cshtml
@model IEnumerable<QLLaCoffee.Models.GoodsCategories>

@{
    int count = 1;
    ViewBag.Title = "Danh sách loại mặt hàng";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}


<div class="card">
    <div class="card-body">
        <div class="d-flex justify-content-between mb-2">
            <p class="card-title">Danh sách loại mặt hàng</p>
            <div>
                <button class="btn btn-danger" id="btnDeleteAll">
                    <i class="ti-trash"></i>
                </button>
                <a href="@Url.Action("Create", "GoodsCategories")" class="btn btn-success ml-2">
                    <i class="ti-plus"></i>
                </a>
            </div>
        </div>

        @using (Html.BeginForm(FormMethod.Post))
        {
            <div class="d-flex align-items-center mb-2 w-75">
                <label>Loại mặt hàng:</label>
                <input class="form-control w-50 ml-2" type="text" placeholder="Tên loại mặt hàng" name="goodsCategoryName" value="@ViewBag.GoodsCategoryName">
                <button class="btn btn-info ml-2" type="submit">
                    Tìm kiếm
                </button>
                <a href="@Url.Action("Index", "GoodsCategories")" class="btn btn-secondary ml-2">
                    <i class="mdi mdi-autorenew"></i>
                </a>
            </div>
        }

        <div>
            <table class="table table-striped table-hover">
                <thead>
                    <tr style="background-color: dodgerblue; color: white;">
                        <th>
                            <div class="form-check">
                                <label class="form-check-label">
                                    <input type="checkbox" class="form-check-input" id="SelectAll">
                                </label>
                            </div>
                        </th>
                        <th style="vertical-align: middle;">#</th>
                        <th style="vertical-align: middle;">
                            @Html.DisplayNameFor(model => model.GoodsCategoryName)
                        </th>
                        <th style="vertical-align: middle;">
                            @Html.DisplayNameFor(model => model.GoodsCategoryDescription)
                        </th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    @if (!Model.Any())
                    {
                        <tr>
                            <td colspan="8" class="text-center">Không có dữ liệu</td>
                        </tr>
                    }
                    else
                    {
                        foreach (var item in Model)
                        {
                            <tr>
                                <td>
                                    <div class="form-check">
                                        <label class="form-check-label">
                                            <input type="checkbox" class="form-check-input cbkItem" value="@item.GoodsCategoryID">
                                        </label>
                                    </div>
                                </td>
                                <td>@(count++)</td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.GoodsCategoryName)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.GoodsCategoryDescription)
                                </td>
                                <td>
                                    <a href="@Url.Action("Edit", "GoodsCategories", new { id = item.GoodsCategoryID })" style="text-decoration: none; margin-right: 20px">
                                        <i class="mdi mdi-pencil" style="font-size: 25px; color: dodgerblue;"></i>
                                    </a>
                                    <a href="" style="text-decoration: none" class="btnDelete">
                                        <i class="mdi mdi-delete" style="font-size: 25px; color: red"></i>
                                    </a>
                                </td>
                            </tr>
                        }
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>


@section Scripts {
    <script>
        function checkDeleteButtonVisibility() {
            var anyChecked = $('.cbkItem:checked').length > 0 || $('#SelectAll').prop('checked');;
            $('#btnDeleteAll').toggle(anyChecked);
        }
        $(document).ready(function () {
            checkDeleteButtonVisibility();
            $('body').on('change', '.cbkItem', function () {
                checkDeleteButtonVisibility();
            });
            $('body').on('click', '#btnDeleteAll', function (e) {
                e.preventDefault()
                var str = "";
                var checkbox = $(this).parents('.card-body').find('td input:checkbox');
                var i = 0;
                checkbox.each(function () {
                    if (this.checked) {
                        checkbox.attr('selected', 'checked');
                        var _id = $(this).val();
                        if (i == 0) {
                            str += _id;
                        } else {
                            str += "," + _id;
                        }
                        i++
                    } else {
                        checkbox.attr('selected', '');
                    }
                });
                if (str.length > 0) {
                    Swal.fire({
                        title: 'Bạn có chắc chắn muốn xóa các bản ghi này? (Xóa các bản ghi này sẽ xóa các bản ghi liên quan từ các bảng khác)',
                        icon: 'warning',
                        showCancelButton: true,
                        confirmButtonText: 'Xóa',
                        cancelButtonText: 'Hủy',
                    }).then((result) => {
                        if (result.isConfirmed) {
                            $.ajax({
                                url: '/GoodsCategories/DeleteAll',
                                type: 'POST',
                                data: { ids: str },
                                success: function (rs) {
                                    if (rs.success) {
                                        location.reload();
                                    }
                                }
                            });
                        }
                    });
                }
            });
            $('body').on('change', '#SelectAll', function () {
                var checkStatus = this.checked;
                var checkbox = $(this).parents('.card-body').find('td input:checkbox');
                checkbox.each(function () {
                    this.checked = checkStatus;
                    if (this.checked) {
                        checkbox.attr('selected', 'checked');
                        checkDeleteButtonVisibility();
                    } else {
                        checkbox.attr('selected', '');
                        checkDeleteButtonVisibility();
                    }
                });
            });
            // Sự kiện khi nhấn vào biểu tượng rác của từng bản ghi
            $('body').on('click', '.btnDelete', function (e) {
                e.preventDefault();
                var itemId = $(this).closest('tr').find('.cbkItem').val();
                Swal.fire({
                    title: 'Bạn có chắc chắn muốn xóa bản ghi này? (Xóa bản ghi này sẽ xóa các bản ghi liên quan từ các bảng khác)',
                    icon: 'warning',
                    showCancelButton: true,
                    confirmButtonText: 'Xóa',
                    cancelButtonText: 'Hủy',
                }).then((result) => {
                    if (result.isConfirmed) {
                        $.ajax({
                            url: '/GoodsCategories/Delete', // Đường dẫn đến action xóa của controller của bạn
                            type: 'POST', // Hoặc 'GET' tùy thuộc vào cách bạn đã cấu hình controller của mình
                            data: { id: itemId },
                            success: function (rs) {
                                if (rs.success) {
                                    location.reload();
                                }
                            }
                        });
                    }
                });
            });
        });
    </script>
}